presets = [{'name': 'MS Deal 1',
            'tableau': [[{'rank': 11, 'suit': 'diamonds'}, {'rank': 13, 'suit': 'diamonds'}, {'rank': 2, 'suit': 'spades'}, {'rank': 4, 'suit': 'clubs'}, {'rank': 3, 'suit': 'spades'}, {'rank': 6, 'suit': 'diamonds'}, {'rank': 6, 'suit': 'spades'}], [{'rank': 2, 'suit': 'diamonds'}, {'rank': 13, 'suit': 'clubs'}, {'rank': 13, 'suit': 'spades'}, {'rank': 5, 'suit': 'clubs'}, {'rank': 10, 'suit': 'diamonds'}, {'rank': 8, 'suit': 'spades'}, {'rank': 9, 'suit': 'clubs'}], [{'rank': 9, 'suit': 'hearts'}, {'rank': 9, 'suit': 'spades'}, {'rank': 9, 'suit': 'diamonds'}, {'rank': 10, 'suit': 'spades'}, {'rank': 4, 'suit': 'spades'}, {'rank': 8, 'suit': 'diamonds'}, {'rank': 2, 'suit': 'hearts'}], [{'rank': 11, 'suit': 'clubs'}, {'rank': 5, 'suit': 'spades'}, {'rank': 12, 'suit': 'diamonds'}, {'rank': 12, 'suit': 'hearts'}, {'rank': 10, 'suit': 'hearts'}, {'rank': 12, 'suit': 'spades'}, {'rank': 6, 'suit': 'hearts'}], [{'rank': 5, 'suit': 'diamonds'}, {'rank': 1, 'suit': 'diamonds'}, {'rank': 11, 'suit': 'spades'}, {'rank': 4, 'suit': 'hearts'}, {'rank': 8, 'suit': 'hearts'}, {'rank': 6, 'suit': 'clubs'}], [{'rank': 7, 'suit': 'hearts'}, {'rank': 12, 'suit': 'clubs'}, {'rank': 1, 'suit': 'spades'}, {'rank': 1, 'suit': 'clubs'}, {'rank': 2, 'suit': 'clubs'}, {'rank': 3, 'suit': 'diamonds'}], [{'rank': 7, 'suit': 'clubs'}, {'rank': 13, 'suit': 'hearts'}, {'rank': 1, 'suit': 'hearts'}, {'rank': 4, 'suit': 'diamonds'}, {'rank': 11, 'suit': 'hearts'}, {'rank': 8, 'suit': 'clubs'}], [{'rank': 5, 'suit': 'hearts'}, {'rank': 3, 'suit': 'hearts'}, {'rank': 3, 'suit': 'clubs'}, {'rank': 7, 'suit': 'spades'}, {'rank': 7, 'suit': 'diamonds'}, {'rank': 10, 'suit': 'clubs'}]],
            'free_cells': [None, None, None, None],
            'foundations': {'hearts': 0, 'diamonds': 0, 'clubs': 0, 'spades': 0}
        }, 
        {'name': 'MS Deal 3',
            'tableau': [[{'rank': 11, 'suit': 'diamonds'}, {'rank': 13, 'suit': 'diamonds'}, {'rank': 2, 'suit': 'spades'}, {'rank': 4, 'suit': 'clubs'}, {'rank': 3, 'suit': 'spades'}, {'rank': 6, 'suit': 'diamonds'}, {'rank': 6, 'suit': 'spades'}], [{'rank': 2, 'suit': 'diamonds'}, {'rank': 13, 'suit': 'clubs'}, {'rank': 13, 'suit': 'spades'}, {'rank': 5, 'suit': 'clubs'}, {'rank': 10, 'suit': 'diamonds'}, {'rank': 8, 'suit': 'spades'}, {'rank': 9, 'suit': 'clubs'}], [{'rank': 9, 'suit': 'hearts'}, {'rank': 9, 'suit': 'spades'}, {'rank': 9, 'suit': 'diamonds'}, {'rank': 10, 'suit': 'spades'}, {'rank': 4, 'suit': 'spades'}, {'rank': 8, 'suit': 'diamonds'}, {'rank': 2, 'suit': 'hearts'}], [{'rank': 11, 'suit': 'clubs'}, {'rank': 5, 'suit': 'spades'}, {'rank': 12, 'suit': 'diamonds'}, {'rank': 12, 'suit': 'hearts'}, {'rank': 10, 'suit': 'hearts'}, {'rank': 12, 'suit': 'spades'}, {'rank': 6, 'suit': 'hearts'}], [{'rank': 5, 'suit': 'diamonds'}, {'rank': 1, 'suit': 'diamonds'}, {'rank': 11, 'suit': 'spades'}, {'rank': 4, 'suit': 'hearts'}, {'rank': 8, 'suit': 'hearts'}, {'rank': 6, 'suit': 'clubs'}], [{'rank': 7, 'suit': 'hearts'}, {'rank': 12, 'suit': 'clubs'}, {'rank': 1, 'suit': 'spades'}, {'rank': 1, 'suit': 'clubs'}, {'rank': 2, 'suit': 'clubs'}, {'rank': 3, 'suit': 'diamonds'}], [{'rank': 7, 'suit': 'clubs'}, {'rank': 13, 'suit': 'hearts'}, {'rank': 1, 'suit': 'hearts'}, {'rank': 4, 'suit': 'diamonds'}, {'rank': 11, 'suit': 'hearts'}, {'rank': 8, 'suit': 'clubs'}], [{'rank': 5, 'suit': 'hearts'}, {'rank': 3, 'suit': 'hearts'}, {'rank': 3, 'suit': 'clubs'}, {'rank': 7, 'suit': 'spades'}, {'rank': 7, 'suit': 'diamonds'}, {'rank': 10, 'suit': 'clubs'}]],
            'free_cells': [None, None, None, None],
            'foundations': {'hearts': 0, 'diamonds': 0, 'clubs': 0, 'spades': 0}
        }]

for preset in presets:
    print(preset['name'])
